# Generated by Django 5.0.4 on 2024-06-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=30)),
                ('pqty', models.IntegerField()),
                ('pdesc', models.TextField()),
                ('pimg', models.ImageField(upload_to='')),
            ],
        ),
    ]
